let orbMetalHead = #"""
// Generated from effect.wgsl for the native SwiftUI/Metal export.
// Do not edit this file independently of the WGSL source.
// language: metal2.1
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;
using metal::uint;
struct DefaultConstructible {
    template<typename T>
    operator T() && {
        return T {};
    }
};

struct Uniforms {
    metal::float2 size;
    float time;
    float speed;
    float radius;
    float zoom;
    float warp;
    float ridgeAmt;
    float sharp;
    float shade;
    float sheen;
    float gloss;
    float shellMidAlpha;
    float shellEdgeAlpha;
    float exposure;
    float style;
    float edgeSoftness;
    float edgeGlow;
    float paletteCount;
    float glassEnabled;
    float glassOpacity;
    float contourDeform;
    float bandDensity;
    float chromaticShift;
    float metalScale;
    float metalStretch;
    float metalAngle;
    float metalOffset;
    float metalPhase;
    float metalEvolution;
    float metalRoughness;
    float metalDepth;
    float particleDensity;
    float ribbonCount;
    float ribbonWidth;
    float ribbonTwist;
    float ribbonFold;
    float ribbonBreath;
    float particleSize;
    float particleBloom;
    metal::float4 colorA;
    metal::float4 colorB;
    metal::float4 colorC;
    metal::float4 colorD;
    metal::float4 highlightColor;
    metal::float4 shellInner;
    metal::float4 shellMid;
    metal::float4 shellEdge;
    metal::float4 sheenColor;
    metal::float4 specColor;
    metal::float4 canvasColor;
    metal::float4 glowColor;
    metal::float4 paletteStop0_;
    metal::float4 paletteStop1_;
    metal::float4 paletteStop2_;
    metal::float4 paletteStop3_;
    metal::float4 paletteStop4_;
    metal::float4 paletteStop5_;
    metal::float4 paletteStop6_;
    metal::float4 paletteStop7_;
    metal::float4 paletteStop8_;
    metal::float4 paletteStop9_;
    metal::float4 paletteStop10_;
    metal::float4 paletteStop11_;
};
struct MfRamp {
    float n;
    char _pad1[12];
    metal::float3 s0_;
    metal::float3 s1_;
    metal::float3 s2_;
    metal::float3 s3_;
    metal::float3 s4_;
    metal::float3 s5_;
    metal::float3 s6_;
    metal::float3 s7_;
    metal::float3 s8_;
    metal::float3 s9_;
    metal::float3 s10_;
    metal::float3 s11_;
};
struct VOut {
    metal::float4 pos;
    metal::float2 uv;
    char _pad2[8];
};
struct type_7 {
    metal::float2 inner[3];
};
constant float GL_FU = 0.8817204;
constant float GL_BSIG_CLEAR = 0.018;
constant float GL_BSIG_GLASS = 0.0399;
constant float GL_KA = 6.0;
constant float GL_KG = 4.1209;
constant float GL_KWA = 0.5;
constant float GL_KR = 0.32;
constant float GL_GH = 1.7320508;
constant float GL_CLEAR_EA = 0.995;
constant float GL_CLEAR_EB = 1.04;

float mfEdgeD(
    float soft
) {
    return soft - 0.005;
}

metal::float3 mfEdgeGlow(
    metal::float3 col,
    metal::float2 uv,
    metal::float2 ctr,
    float rad,
    float soft_1,
    float glow,
    metal::float3 glowRGB
) {
    if (glow <= 0.0) {
        return col;
    }
    float r_3 = metal::length(uv - ctr);
    float outside = metal::smoothstep(rad - metal::max(soft_1, 0.0005), rad + metal::max(soft_1, 0.0005), r_3);
    return col + (glowRGB * ((glow * metal::exp(-(metal::max(r_3 - rad, 0.0)) * 11.0)) * outside));
}

metal::float3 mfRampPick(
    float idx,
    metal::float3 s0_,
    metal::float3 s1_,
    metal::float3 s2_,
    metal::float3 s3_,
    metal::float3 s4_,
    metal::float3 s5_,
    metal::float3 s6_,
    metal::float3 s7_,
    metal::float3 s8_,
    metal::float3 s9_,
    metal::float3 s10_,
    metal::float3 s11_
) {
    metal::float3 r = {};
    r = s0_;
    metal::float3 _e14 = r;
    r = (idx == 1.0) ? s1_ : _e14;
    metal::float3 _e18 = r;
    r = (idx == 2.0) ? s2_ : _e18;
    metal::float3 _e22 = r;
    r = (idx == 3.0) ? s3_ : _e22;
    metal::float3 _e26 = r;
    r = (idx == 4.0) ? s4_ : _e26;
    metal::float3 _e30 = r;
    r = (idx == 5.0) ? s5_ : _e30;
    metal::float3 _e34 = r;
    r = (idx == 6.0) ? s6_ : _e34;
    metal::float3 _e38 = r;
    r = (idx == 7.0) ? s7_ : _e38;
    metal::float3 _e42 = r;
    r = (idx == 8.0) ? s8_ : _e42;
    metal::float3 _e46 = r;
    r = (idx == 9.0) ? s9_ : _e46;
    metal::float3 _e50 = r;
    r = (idx == 10.0) ? s10_ : _e50;
    metal::float3 _e54 = r;
    r = (idx == 11.0) ? s11_ : _e54;
    metal::float3 _e58 = r;
    return _e58;
}

metal::float3 mfRampCyc(
    float tIn,
    float n,
    metal::float3 s0_1,
    metal::float3 s1_1,
    metal::float3 s2_1,
    metal::float3 s3_1,
    metal::float3 s4_1,
    metal::float3 s5_1,
    metal::float3 s6_1,
    metal::float3 s7_1,
    metal::float3 s8_1,
    metal::float3 s9_1,
    metal::float3 s10_1,
    metal::float3 s11_1
) {
    float k_3 = metal::clamp(metal::floor(n + 0.5), 1.0, 12.0);
    float x = metal::fract(tIn) * k_3;
    float i0_ = metal::min(metal::floor(x), k_3 - 1.0);
    float i1_ = ((i0_ + 1.0) >= k_3) ? 0.0 : i0_ + 1.0;
    metal::float3 _e33 = mfRampPick(i0_, s0_1, s1_1, s2_1, s3_1, s4_1, s5_1, s6_1, s7_1, s8_1, s9_1, s10_1, s11_1);
    metal::float3 _e34 = mfRampPick(i1_, s0_1, s1_1, s2_1, s3_1, s4_1, s5_1, s6_1, s7_1, s8_1, s9_1, s10_1, s11_1);
    return metal::mix(_e33, _e34, x - i0_);
}

metal::float3 mfRampLin(
    float tIn_1,
    float n_1,
    metal::float3 s0_2,
    metal::float3 s1_2,
    metal::float3 s2_2,
    metal::float3 s3_2,
    metal::float3 s4_2,
    metal::float3 s5_2,
    metal::float3 s6_2,
    metal::float3 s7_2,
    metal::float3 s8_2,
    metal::float3 s9_2,
    metal::float3 s10_2,
    metal::float3 s11_2
) {
    float k_4 = metal::clamp(metal::floor(n_1 + 0.5), 1.0, 12.0);
    float x_1 = metal::clamp(tIn_1, 0.0, 1.0) * (k_4 - 1.0);
    float i0_1 = metal::clamp(metal::floor(x_1), 0.0, metal::max(k_4 - 2.0, 0.0));
    metal::float3 _e33 = mfRampPick(i0_1, s0_2, s1_2, s2_2, s3_2, s4_2, s5_2, s6_2, s7_2, s8_2, s9_2, s10_2, s11_2);
    metal::float3 _e36 = mfRampPick(i0_1 + 1.0, s0_2, s1_2, s2_2, s3_2, s4_2, s5_2, s6_2, s7_2, s8_2, s9_2, s10_2, s11_2);
    return metal::mix(_e33, _e36, x_1 - i0_1);
}

MfRamp mfRampOf(
    float n_2,
    metal::float3 s0_3,
    metal::float3 s1_3,
    metal::float3 s2_3,
    metal::float3 s3_3,
    metal::float3 s4_3,
    metal::float3 s5_3,
    metal::float3 s6_3,
    metal::float3 s7_3,
    metal::float3 s8_3,
    metal::float3 s9_3,
    metal::float3 s10_3,
    metal::float3 s11_3
) {
    return MfRamp {n_2, {}, s0_3, s1_3, s2_3, s3_3, s4_3, s5_3, s6_3, s7_3, s8_3, s9_3, s10_3, s11_3};
}

metal::float3 mfRampCycR(
    float t,
    MfRamp r_1
) {
    metal::float3 _e15 = mfRampCyc(t, r_1.n, r_1.s0_, r_1.s1_, r_1.s2_, r_1.s3_, r_1.s4_, r_1.s5_, r_1.s6_, r_1.s7_, r_1.s8_, r_1.s9_, r_1.s10_, r_1.s11_);
    return _e15;
}

metal::float3 mfRampLinR(
    float t_1,
    MfRamp r_2
) {
    metal::float3 _e15 = mfRampLin(t_1, r_2.n, r_2.s0_, r_2.s1_, r_2.s2_, r_2.s3_, r_2.s4_, r_2.s5_, r_2.s6_, r_2.s7_, r_2.s8_, r_2.s9_, r_2.s10_, r_2.s11_);
    return _e15;
}

float lqHash(
    metal::float2 pIn
) {
    metal::float2 p_1 = {};
    p_1 = metal::fract(pIn * metal::float2(123.34, 456.21));
    metal::float2 _e7 = p_1;
    metal::float2 _e8 = p_1;
    metal::float2 _e9 = p_1;
    p_1 = _e7 + metal::float2(metal::dot(_e8, _e9 + metal::float2(45.32)));
    float _e17 = p_1.x;
    float _e19 = p_1.y;
    return metal::fract(_e17 * _e19);
}

float lqNoise(
    metal::float2 p_2
) {
    metal::float2 f = {};
    metal::float2 i_4 = metal::floor(p_2);
    f = metal::fract(p_2);
    metal::float2 _e4 = f;
    metal::float2 _e5 = f;
    metal::float2 _e7 = f;
    f = (_e4 * _e5) * (metal::float2(3.0) - (2.0 * _e7));
    float _e14 = lqHash(i_4);
    float _e19 = lqHash(i_4 + metal::float2(1.0, 0.0));
    float _e21 = f.x;
    float _e27 = lqHash(i_4 + metal::float2(0.0, 1.0));
    float _e32 = lqHash(i_4 + metal::float2(1.0, 1.0));
    float _e34 = f.x;
    float _e37 = f.y;
    return metal::mix(metal::mix(_e14, _e19, _e21), metal::mix(_e27, _e32, _e34), _e37);
}

metal::float2 lqFbm(
    metal::float2 pIn_1,
    float bs
) {
    metal::float2 p_3 = {};
    float s = 0.0;
    float a = 0.5;
    float m = 0.0;
    float vr = 0.0;
    float g = 1.0;
    int i_1 = 0;
    p_3 = pIn_1;
    float e = (-6.0 * bs) * bs;
    uint2 loop_bound = uint2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (metal::all(loop_bound == uint2(0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            int _e74 = i_1;
            i_1 = as_type<int>(as_type<uint>(_e74) + as_type<uint>(1));
        }
        loop_init = false;
        int _e18 = i_1;
        if (_e18 < 5) {
        } else {
            break;
        }
        {
            float _e21 = g;
            float b_1 = metal::exp(e * _e21);
            float _e24 = s;
            float _e25 = a;
            metal::float2 _e26 = p_3;
            float _e27 = lqNoise(_e26);
            s = _e24 + (_e25 * (0.5 + (b_1 * (_e27 - 0.5))));
            float _e35 = vr;
            float _e36 = a;
            float _e37 = a;
            vr = _e35 + ((_e36 * _e37) * (1.0 - (b_1 * b_1)));
            float _e44 = m;
            float _e45 = a;
            m = _e44 + _e45;
            float _e47 = a;
            a = _e47 * 0.5;
            float _e50 = g;
            g = _e50 * GL_KG;
            float _e54 = p_3.x;
            float _e58 = p_3.y;
            float _e63 = p_3.x;
            float _e67 = p_3.y;
            p_3 = metal::float2((0.8 * _e54) - (0.6 * _e58), (0.6 * _e63) + (0.8 * _e67)) * 2.03;
        }
    }
    float _e77 = s;
    float _e78 = m;
    float _e81 = vr;
    float _e84 = m;
    return metal::float2(_e77 / _e78, (GL_KR * metal::sqrt(_e81)) / _e84);
}

float lqRidge(
    float v,
    float k
) {
    return metal::pow(metal::clamp(1.0 - metal::abs((v * 2.0) - 1.0), 0.0, 1.0), k);
}

metal::float3 lqRamp(
    float v_1,
    metal::float3 cA,
    metal::float3 cB,
    metal::float3 cC,
    metal::float3 cD,
    constant Uniforms& u
) {
    metal::float3 c = {};
    c = metal::mix(cA, cB, metal::smoothstep(0.0, 0.45, v_1));
    metal::float3 _e10 = c;
    c = metal::mix(_e10, cC, metal::smoothstep(0.38, 0.72, v_1));
    metal::float3 _e15 = c;
    c = metal::mix(_e15, cD, metal::smoothstep(0.68, 1.0, v_1));
    metal::float3 _e20 = c;
    float _e23 = u.paletteCount;
    metal::float4 _e26 = u.paletteStop0_;
    metal::float4 _e30 = u.paletteStop1_;
    metal::float4 _e34 = u.paletteStop2_;
    metal::float4 _e38 = u.paletteStop3_;
    metal::float4 _e42 = u.paletteStop4_;
    metal::float4 _e46 = u.paletteStop5_;
    metal::float4 _e50 = u.paletteStop6_;
    metal::float4 _e54 = u.paletteStop7_;
    metal::float4 _e58 = u.paletteStop8_;
    metal::float4 _e62 = u.paletteStop9_;
    metal::float4 _e66 = u.paletteStop10_;
    metal::float4 _e70 = u.paletteStop11_;
    metal::float3 _e72 = mfRampLin(v_1, _e23, _e26.xyz, _e30.xyz, _e34.xyz, _e38.xyz, _e42.xyz, _e46.xyz, _e50.xyz, _e54.xyz, _e58.xyz, _e62.xyz, _e66.xyz, _e70.xyz);
    float _e75 = u.paletteCount;
    return (_e75 > 0.5) ? _e72 : _e20;
}

float lqRidgeS(
    metal::float2 vs,
    float k_1
) {
    float d_1 = GL_GH * vs.y;
    float _e7 = lqRidge(vs.x - d_1, k_1);
    float _e9 = lqRidge(vs.x, k_1);
    float _e15 = lqRidge(vs.x + d_1, k_1);
    return ((_e7 + (4.0 * _e9)) + _e15) / 6.0;
}

float lqStepS(
    metal::float2 vs_1,
    float a_1,
    float b
) {
    float d_2 = GL_GH * vs_1.y;
    return ((metal::smoothstep(a_1, b, vs_1.x - d_2) + (4.0 * metal::smoothstep(a_1, b, vs_1.x))) + metal::smoothstep(a_1, b, vs_1.x + d_2)) / 6.0;
}

float lqPowS(
    metal::float2 vs_2,
    float k_2
) {
    float d_3 = GL_GH * vs_2.y;
    return ((metal::pow(metal::clamp(vs_2.x - d_3, 0.0, 1.0), k_2) + (4.0 * metal::pow(metal::clamp(vs_2.x, 0.0, 1.0), k_2))) + metal::pow(metal::clamp(vs_2.x + d_3, 0.0, 1.0), k_2)) / 6.0;
}

metal::float3 glsFinishPresetFluid(
    metal::float3 colorIn,
    metal::float2 p_4,
    constant Uniforms& u
) {
    metal::float3 color = {};
    color = colorIn;
    metal::float3 _e3 = color;
    metal::float4 _e6 = u.highlightColor;
    float _e10 = u.shade;
    color = metal::mix(_e3, _e6.xyz, (_e10 * 0.22) * metal::smoothstep(0.15, 1.15, metal::dot(p_4, metal::float2(-0.32, 0.78))));
    metal::float3 _e22 = color;
    float _e25 = u.shade;
    color = _e22 * (1.0 - ((_e25 * 0.34) * metal::smoothstep(-0.1, 1.2, metal::dot(p_4, metal::float2(0.45, -0.62)))));
    metal::float3 _e39 = color;
    float _e42 = u.shade;
    color = _e39 * (1.0 - ((_e42 * 0.22) * metal::smoothstep(0.72, 1.08, metal::length(p_4))));
    metal::float3 _e53 = color;
    return metal::clamp(_e53, metal::float3(0.0), metal::float3(1.0));
}

metal::float3 glsFinishEmissionFluid(
    metal::float3 colorIn,
    metal::float2 p,
    constant Uniforms& u
) {
    metal::float3 color = colorIn;
    if (u.glassEnabled > 0.5) {
        color = metal::mix(
            color,
            u.highlightColor.xyz,
            u.shade * 0.22
                * metal::smoothstep(0.15, 1.15, metal::dot(p, metal::float2(-0.32, 0.78)))
        );
    }
    color *= 1.0 - u.shade * 0.34
        * metal::smoothstep(-0.1, 1.2, metal::dot(p, metal::float2(0.45, -0.62)));
    color *= 1.0 - u.shade * 0.22
        * metal::smoothstep(0.72, 1.08, metal::length(p));
    return metal::clamp(color, metal::float3(0.0), metal::float3(1.0));
}

metal::float2 glsSiriBand(
    metal::float2 q,
    float drift,
    float phaseOffset,
    float amplitude,
    float mainY,
    float envelope,
    float softness
) {
    float y = (amplitude * envelope) * metal::sin(((q.x * 1.0) + drift) + phaseOffset);
    float distanceToLine = metal::abs(q.y - y);
    float line = 0.018 / (metal::sqrt((distanceToLine * distanceToLine) + (softness * softness)) + 0.026);
    float bandDistance = metal::max(0.0, metal::max(q.y - metal::max(mainY, y), metal::min(mainY, y) - q.y));
    float band = 0.018 / (bandDistance + 0.075);
    return metal::float2(line, band);
}

metal::float3 glsSiriFluid(
    metal::float2 p_5,
    float t_2,
    constant Uniforms& u
) {
    metal::float3 color_1 = {};
    float _e4 = u.zoom;
    float scale_1 = 0.74 + (_e4 * 0.34);
    metal::float2 q_5 = p_5 / metal::float2(scale_1);
    float xNorm = q_5.x;
    float envelopeBase = metal::cos(1.5707964 * metal::min(metal::abs(0.9 * xNorm), 1.0));
    float envelope_1 = envelopeBase * envelopeBase;
    float low = 0.5 + (0.5 * metal::cos(t_2 * 0.37));
    float mid = 0.5 + (0.5 * metal::sin((t_2 * 0.51) + 1.2));
    float high = 0.5 + (0.5 * metal::cos((t_2 * 0.73) + 2.1));
    float drift_1 = t_2 * 2.4;
    float _e50 = u.ridgeAmt;
    float mainAmplitude = (0.25 + (_e50 * 0.075)) + (low * 0.018);
    float bandAmplitude = (mainAmplitude + (mid * 0.025)) + (high * 0.018);
    float mainY_1 = (mainAmplitude * envelope_1) * metal::sin((q_5.x * 1.1) + drift_1);
    float _e73 = u.warp;
    float separation = (1.85 + (_e73 * 0.2)) + (mid * 0.28);
    float _e83 = u.ridgeAmt;
    float softness_2 = (0.035 + ((1.0 - _e83) * 0.018)) + (mid * 0.006);
    metal::float2 _e94 = glsSiriBand(q_5, drift_1, -(separation), bandAmplitude, mainY_1, envelope_1, softness_2);
    metal::float2 _e98 = glsSiriBand(q_5, drift_1, -(separation) * 0.34, bandAmplitude, mainY_1, envelope_1, softness_2);
    metal::float2 _e101 = glsSiriBand(q_5, drift_1, separation * 0.34, bandAmplitude, mainY_1, envelope_1, softness_2);
    metal::float2 _e102 = glsSiriBand(q_5, drift_1, separation, bandAmplitude, mainY_1, envelope_1, softness_2);
    float w0_ = _e94.x + _e94.y;
    float w1_ = _e98.x + _e98.y;
    float w2_ = _e101.x + _e101.y;
    float w3_ = _e102.x + _e102.y;
    float total = ((w0_ + w1_) + w2_) + w3_;
    float dominant0_ = w0_ * w0_;
    float dominant1_ = w1_ * w1_;
    float dominant2_ = w2_ * w2_;
    float dominant3_ = w3_ * w3_;
    float dominantTotal = ((dominant0_ + dominant1_) + dominant2_) + dominant3_;
    metal::float4 _e127 = u.colorA;
    metal::float4 _e132 = u.colorC;
    metal::float4 _e138 = u.colorB;
    metal::float4 _e144 = u.colorD;
    metal::float3 spectral = ((((_e127.xyz * dominant0_) + (_e132.xyz * dominant1_)) + (_e138.xyz * dominant2_)) + (_e144.xyz * dominant3_)) / metal::float3(metal::max(dominantTotal, 0.0001));
    float energy = (1.0 - metal::exp(-(total) * 0.58)) * envelope_1;
    float mainDistance = metal::abs(q_5.y - mainY_1);
    float whiteCore = metal::exp((-(mainDistance) * mainDistance) / 0.0028) * envelope_1;
    metal::float4 _e170 = u.colorD;
    metal::float4 _e174 = u.colorB;
    float glassFill = u.glassEnabled > 0.5 ? 1.0 : 0.0;
    metal::float3 atmosphere = metal::mix(
        _e170.xyz, _e174.xyz, metal::smoothstep(-0.7, 0.7, q_5.y)) * 0.018 * glassFill;
    color_1 = atmosphere + ((spectral * energy) * 1.14);
    metal::float3 _e188 = color_1;
    metal::float4 _e191 = u.highlightColor;
    color_1 = _e188 + ((_e191.xyz * whiteCore) * (0.18 + (0.1 * low)));
    float emissionMask = metal::mix(
        metal::smoothstep(0.08, 0.25, energy + whiteCore * 0.12),
        1.0,
        glassFill
    );
    color_1 *= emissionMask;
    metal::float3 _e200 = color_1;
    metal::float3 _e203 = color_1;
    color_1 = _e200 / (metal::float3(1.0) + (_e203 * 0.18));
    metal::float3 _e208 = color_1;
    metal::float3 _e209 = glsFinishEmissionFluid(_e208, p_5, u);
    return _e209;
}

float glsSpectrumHeight(
    metal::float2 q_1,
    float t_3,
    float frequency,
    float phaseOffset_1,
    float amplitude_1
) {
    float x_2 = q_1.x * 2.15;
    float envelope_2 = metal::pow(4.0 / (4.0 + (x_2 * x_2)), 4.0);
    float breathing = 0.82 + (0.18 * metal::sin((t_3 * 0.48) + (phaseOffset_1 * 0.7)));
    float wave = metal::abs(metal::sin(((frequency * x_2) - (t_3 * 1.36)) + phaseOffset_1));
    return ((envelope_2 * amplitude_1) * breathing) * (0.28 + (0.72 * wave));
}

float glsSpectrumLayer(
    metal::float2 q_2,
    float height,
    float softness_1
) {
    return (1.0 - metal::smoothstep(metal::max(height - softness_1, 0.0), height + softness_1, metal::abs(q_2.y))) * metal::smoothstep(0.0, 0.045, height);
}

metal::float3 glsSpectrumFluid(
    metal::float2 p_6,
    float t_4,
    constant Uniforms& u
) {
    metal::float3 color_2 = {};
    float _e4 = u.zoom;
    float scale_2 = 0.74 + (_e4 * 0.34);
    metal::float2 q_6 = p_6 / metal::float2(scale_2);
    float _e13 = u.ridgeAmt;
    float amplitude_2 = 0.26 + (_e13 * 0.27);
    float _e20 = u.warp;
    float frequency_1 = 0.72 + (_e20 * 0.095);
    float _e27 = u.ridgeAmt;
    float softness_3 = 0.026 + ((1.0 - _e27) * 0.032);
    float _e39 = glsSpectrumHeight(q_6, t_4, frequency_1 * 0.82, -1.2, amplitude_2 * 0.72);
    float _e41 = glsSpectrumHeight(q_6, t_4, frequency_1, 0.45, amplitude_2);
    float _e47 = glsSpectrumHeight(q_6, t_4, frequency_1 * 1.17, 2.05, amplitude_2 * 0.82);
    float _e48 = glsSpectrumLayer(q_6, _e39, softness_3);
    float _e49 = glsSpectrumLayer(q_6, _e41, softness_3);
    float _e50 = glsSpectrumLayer(q_6, _e47, softness_3);
    float spectrumX = q_6.x * 2.15;
    float envelope_3 = metal::pow(4.0 / (4.0 + (spectrumX * spectrumX)), 4.0);
    float support = metal::exp((-(q_6.y) * q_6.y) / 0.00072) * envelope_3;
    float total_1 = (_e48 + _e49) + _e50;
    metal::float4 _e73 = u.colorB;
    metal::float4 _e78 = u.colorC;
    metal::float4 _e84 = u.colorD;
    metal::float3 spectral_1 = (((_e73.xyz * _e48) + (_e78.xyz * _e49)) + (_e84.xyz * _e50)) / metal::float3(metal::max(total_1, 0.001));
    metal::float4 _e94 = u.colorD;
    float glassFill = u.glassEnabled > 0.5 ? 1.0 : 0.0;
    color_2 = (_e94.xyz * 0.025 * glassFill)
            + (spectral_1 * (1.0 - metal::exp(-(total_1) * 0.86)));
    metal::float3 _e107 = color_2;
    metal::float4 _e110 = u.colorA;
    color_2 = _e107 + ((_e110.xyz * support) * 0.58);
    metal::float3 _e116 = color_2;
    metal::float3 _e119 = color_2;
    color_2 = _e116 / (metal::float3(1.0) + (_e119 * 0.2));
    metal::float3 _e124 = color_2;
    metal::float3 _e125 = glsFinishEmissionFluid(_e124, p_6, u);
    return _e125;
}

float glsAuroraLayer(
    metal::float2 p_7,
    float t_5,
    float offset,
    constant Uniforms& u
) {
    float drift_2 = (t_5 * 0.18) + (offset * 2.5);
    float _e11 = u.warp;
    float wave1_ = metal::sin(((p_7.x * (2.0 + (_e11 * 0.13))) + drift_2) + (offset * 6.0)) * 0.25;
    float wave2_ = metal::sin(((p_7.x * 3.7) + (drift_2 * 1.3)) + (offset * 4.0)) * 0.12;
    float wave3_ = metal::sin(((p_7.x * 7.2) + (drift_2 * 0.7)) + (offset * 8.0)) * 0.055;
    metal::float2 _e62 = lqFbm(metal::float2((p_7.x * 1.6) + (drift_2 * 0.35), (p_7.y * 0.8) + (offset * 3.0)), 0.018);
    float noiseValue = _e62.x;
    float center = ((((offset * 0.46) + wave1_) + wave2_) + wave3_) + ((noiseValue - 0.5) * 0.28);
    float dist = metal::abs(p_7.y - center);
    float _e81 = u.ridgeAmt;
    float glow_1 = metal::exp((-(dist) * dist) * (13.0 - (5.0 * _e81)));
    metal::float2 _e102 = lqFbm(metal::float2((p_7.x * 4.0) + (t_5 * 0.22), (p_7.y * 7.0) + (offset * 5.0)), 0.012);
    float shimmer = _e102.x;
    return glow_1 * (0.64 + (0.36 * shimmer));
}

metal::float3 glsAuroraFluid(
    metal::float2 p_8,
    float t_6,
    constant Uniforms& u
) {
    metal::float3 color_3 = {};
    float _e4 = u.zoom;
    metal::float2 q_7 = p_8 * (0.82 + (_e4 * 0.58));
    float _e11 = glsAuroraLayer(q_7, t_6, -0.72, u);
    float _e13 = glsAuroraLayer(q_7, t_6, 0.0, u);
    float _e15 = glsAuroraLayer(q_7, t_6, 0.72, u);
    metal::float4 _e18 = u.colorA;
    color_3 = _e18.xyz * (0.46 + (0.18 * (q_7.y + 1.0)));
    metal::float3 _e29 = color_3;
    metal::float4 _e32 = u.colorB;
    color_3 = _e29 + ((_e32.xyz * _e11) * 1.3);
    metal::float3 _e38 = color_3;
    metal::float4 _e41 = u.colorC;
    color_3 = _e38 + ((_e41.xyz * _e13) * 1.15);
    metal::float3 _e47 = color_3;
    metal::float4 _e50 = u.colorD;
    color_3 = _e47 + ((_e50.xyz * _e15) * 1.2);
    metal::float3 _e56 = color_3;
    metal::float4 _e59 = u.colorB;
    metal::float4 _e63 = u.colorD;
    color_3 = _e56 + ((metal::mix(_e59.xyz, _e63.xyz, 0.5) * metal::min(_e11 * _e15, _e13)) * 0.65);
    metal::float2 starUv = (q_7 + metal::float2(1.0)) * 18.0;
    metal::float2 starCell = metal::floor(starUv);
    float _e79 = lqHash(starCell);
    float starPoint = metal::exp(-(metal::dot(metal::fract(starUv) - metal::float2(0.5), metal::fract(starUv) - metal::float2(0.5))) * 90.0);
    float stars = (metal::step(0.965, _e79) * starPoint) * (0.55 + (0.45 * metal::sin((t_6 * (1.0 + (_e79 * 2.0))) + (_e79 * 6.28))));
    metal::float3 _e110 = color_3;
    metal::float4 _e113 = u.highlightColor;
    color_3 = _e110 + ((_e113.xyz * stars) * (1.0 - metal::clamp((_e11 + _e13) + _e15, 0.0, 1.0)));
    metal::float3 _e125 = color_3;
    metal::float3 _e128 = color_3;
    color_3 = _e125 / (metal::float3(1.0) + (_e128 * 0.28));
    metal::float3 _e133 = color_3;
    metal::float3 _e134 = glsFinishPresetFluid(_e133, p_8, u);
    return _e134;
}

metal::float2 glsRotate(
    metal::float2 p_9,
    float angle
) {
    float c_1 = metal::cos(angle);
    float s_1 = metal::sin(angle);
    return metal::float2((c_1 * p_9.x) - (s_1 * p_9.y), (s_1 * p_9.x) + (c_1 * p_9.y));
}

float glsNeuroShape(
    metal::float2 pIn_2,
    float t_7,
    constant Uniforms& u
) {
    metal::float2 p_10 = {};
    metal::float2 sineAccum = metal::float2(0.0);
    metal::float2 result = metal::float2(0.0);
    float scale = 8.0;
    int j = 0;
    float _e4 = u.zoom;
    p_10 = pIn_2 * (0.34 + (0.08 * _e4));
    uint2 loop_bound_1 = uint2(4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (metal::all(loop_bound_1 == uint2(0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            int _e60 = j;
            j = as_type<int>(as_type<uint>(_e60) + as_type<uint>(1));
        }
        loop_init_1 = false;
        int _e21 = j;
        if (_e21 < 11) {
        } else {
            break;
        }
        {
            metal::float2 _e24 = p_10;
            metal::float2 _e26 = glsRotate(_e24, 1.0);
            p_10 = _e26;
            metal::float2 _e27 = sineAccum;
            metal::float2 _e29 = glsRotate(_e27, 1.0);
            sineAccum = _e29;
            metal::float2 _e30 = p_10;
            float _e31 = scale;
            int _e33 = j;
            metal::float2 _e37 = sineAccum;
            metal::float2 layer = (((_e30 * _e31) + metal::float2(static_cast<float>(_e33))) + _e37) - metal::float2(t_7 * 0.34);
            metal::float2 _e43 = sineAccum;
            sineAccum = _e43 + metal::sin(layer);
            metal::float2 _e46 = result;
            float _e53 = scale;
            result = _e46 + ((metal::float2(0.5) + (0.5 * metal::cos(layer))) / metal::float2(_e53));
            float _e57 = scale;
            scale = _e57 * 1.16;
        }
    }
    float _e64 = result.x;
    float _e66 = result.y;
    return _e64 + _e66;
}

metal::float3 glsPlasmaFluid(
    metal::float2 p_11,
    float t_8,
    constant Uniforms& u
) {
    metal::float3 color_4 = {};
    float _e2 = glsNeuroShape(p_11, t_8, u);
    float _e5 = u.warp;
    float phase = (((_e2 * (10.0 + _e5)) + (p_11.x * 1.7)) - (p_11.y * 1.3)) - (t_8 * 0.52);
    float _e22 = u.ridgeAmt;
    float ridgeWidth = 0.62 - (0.24 * _e22);
    float _e32 = u.sharp;
    float primary = metal::pow(metal::abs(metal::cos(phase)), metal::max(1.3, _e32 * ridgeWidth));
    float _e52 = u.sharp;
    float secondary = metal::pow(metal::abs(metal::cos(((phase * 0.53) + (metal::atan2(p_11.y, p_11.x) * 2.0)) + (t_8 * 0.21))), metal::max(1.6, _e52 * (ridgeWidth + 0.1)));
    float filaments = metal::max(primary, secondary * 0.64);
    float core = metal::pow(primary, 4.0);
    float polarity = 0.5 + (0.5 * metal::sin((phase * 0.37) + (_e2 * 3.0)));
    metal::float4 _e75 = u.colorA;
    metal::float4 _e81 = u.colorD;
    color_4 = metal::mix(_e75.xyz * 0.42, _e81.xyz * 0.48, polarity * 0.46);
    metal::float3 _e89 = color_4;
    metal::float4 _e92 = u.colorB;
    color_4 = metal::mix(_e89, _e92.xyz, filaments * 0.72);
    metal::float3 _e97 = color_4;
    metal::float4 _e100 = u.colorC;
    color_4 = metal::mix(_e97, _e100.xyz, core * 0.68);
    metal::float3 _e105 = color_4;
    metal::float4 _e108 = u.highlightColor;
    color_4 = _e105 + ((_e108.xyz * metal::pow(core, 3.0)) * 0.16);
    metal::float3 _e116 = color_4;
    metal::float3 _e119 = color_4;
    color_4 = _e116 / (metal::float3(1.0) + (_e119 * 0.34));
    metal::float3 _e124 = color_4;
    metal::float3 _e125 = glsFinishPresetFluid(_e124, p_11, u);
    return _e125;
}

metal::float3 glsChromeFluid(
    metal::float2 p_12,
    float t_9,
    constant Uniforms& u
) {
    metal::float2 q_3 = {};
    int i_2 = 1;
    metal::float3 color_5 = {};
    float _e4 = u.zoom;
    q_3 = p_12 * (1.0 + (_e4 * 0.35));
    float _e13 = u.warp;
    float amplitude_3 = 0.028 * _e13;
    uint2 loop_bound_2 = uint2(4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (metal::all(loop_bound_2 == uint2(0u))) { break; }
        loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            int _e53 = i_2;
            i_2 = as_type<int>(as_type<uint>(_e53) + as_type<uint>(1));
        }
        loop_init_2 = false;
        int _e18 = i_2;
        if (_e18 <= 9) {
        } else {
            break;
        }
        {
            int _e21 = i_2;
            float fi = static_cast<float>(_e21);
            float _e25 = q_3.x;
            float _e30 = q_3.y;
            q_3.x = _e25 + ((amplitude_3 / fi) * metal::cos(((fi * 2.7) * _e30) + (t_9 * 0.46)));
            float _e40 = q_3.y;
            float _e45 = q_3.x;
            q_3.y = _e40 + ((amplitude_3 / fi) * metal::cos(((fi * 3.1) * _e45) - (t_9 * 0.4)));
        }
    }
    float _e59 = q_3.y;
    float _e62 = q_3.x;
    float denominator = metal::max(metal::abs(metal::sin(((t_9 * 0.24) - _e59) - _e62)), 0.045);
    float flare = metal::clamp(1.0 / denominator, 0.0, 18.0);
    float metal_ = metal::smoothstep(1.15, 7.5, flare);
    float _e77 = q_3.x;
    float _e79 = q_3.y;
    float _e83 = u.sharp;
    float fold = 0.5 + (0.5 * metal::cos(((_e77 - _e79) * (3.2 + (_e83 * 0.28))) + (t_9 * 0.32)));
    float value = metal::clamp((metal_ * 0.74) + (fold * 0.36), 0.0, 1.0);
    metal::float4 _e107 = u.colorD;
    metal::float4 _e111 = u.colorC;
    metal::float4 _e115 = u.colorB;
    metal::float4 _e119 = u.colorA;
    metal::float3 _e121 = lqRamp(value, _e107.xyz, _e111.xyz, _e115.xyz, _e119.xyz, u);
    color_5 = _e121;
    metal::float3 _e123 = color_5;
    metal::float4 _e126 = u.colorA;
    color_5 = metal::mix(_e123, _e126.xyz, metal::pow(metal_, 5.0) * 0.62);
    metal::float3 _e133 = color_5;
    metal::float3 _e134 = glsFinishPresetFluid(_e133, p_12, u);
    return _e134;
}

"""#
